# Generated by Django 5.2 on 2025-06-28 06:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="プラン名（例: Free, Pro, Enterprise）",
                        max_length=50,
                        unique=True,
                        verbose_name="プラン名",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="表示用のプラン名（例: 無料プラン, プロプラン）",
                        max_length=100,
                        verbose_name="表示名",
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="プランの説明", verbose_name="説明"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="月額料金（USD）",
                        max_digits=10,
                        verbose_name="価格",
                    ),
                ),
                (
                    "daily_audio_limit",
                    models.IntegerField(
                        default=20,
                        help_text="1日の音声生成制限回数",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="日次音声生成制限",
                    ),
                ),
                (
                    "max_audio_duration",
                    models.IntegerField(
                        default=30,
                        help_text="最大音声長（秒）",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(300),
                        ],
                        verbose_name="最大音声長",
                    ),
                ),
                (
                    "max_steps",
                    models.IntegerField(
                        default=200,
                        help_text="最大ステップ数",
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(500),
                        ],
                        verbose_name="最大ステップ数",
                    ),
                ),
                (
                    "can_use_api",
                    models.BooleanField(
                        default=False,
                        help_text="API使用可能",
                        verbose_name="API使用可能",
                    ),
                ),
                (
                    "can_download",
                    models.BooleanField(
                        default=True,
                        help_text="音声ダウンロード可能",
                        verbose_name="ダウンロード可能",
                    ),
                ),
                (
                    "can_edit_audio",
                    models.BooleanField(
                        default=False,
                        help_text="音声編集機能使用可能",
                        verbose_name="音声編集可能",
                    ),
                ),
                (
                    "stripe_price_id",
                    models.CharField(
                        blank=True,
                        help_text="StripeのPrice ID",
                        max_length=100,
                        null=True,
                        verbose_name="Stripe Price ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="アクティブなプランかどうか",
                        verbose_name="アクティブ",
                    ),
                ),
                (
                    "is_popular",
                    models.BooleanField(
                        default=False,
                        help_text="人気プランとして表示するか",
                        verbose_name="人気プラン",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0,
                        help_text="表示順序（小さい順）",
                        verbose_name="表示順序",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "プラン",
                "verbose_name_plural": "プラン",
                "ordering": ["sort_order", "price"],
            },
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(
                        blank=True,
                        help_text="StripeのCustomer ID",
                        max_length=100,
                        null=True,
                        verbose_name="Stripe Customer ID",
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(
                        blank=True,
                        help_text="StripeのSubscription ID",
                        max_length=100,
                        null=True,
                        verbose_name="Stripe Subscription ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "アクティブ"),
                            ("canceled", "キャンセル済み"),
                            ("past_due", "支払い遅延"),
                            ("unpaid", "未払い"),
                            ("trialing", "トライアル中"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "current_period_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="現在期間開始日"
                    ),
                ),
                (
                    "current_period_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="現在期間終了日"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="billing.plan",
                        verbose_name="プラン",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "ユーザーサブスクリプション",
                "verbose_name_plural": "ユーザーサブスクリプション",
            },
        ),
        migrations.CreateModel(
            name="UsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="使用日")),
                (
                    "audio_generations",
                    models.IntegerField(default=0, verbose_name="音声生成回数"),
                ),
                (
                    "api_calls",
                    models.IntegerField(default=0, verbose_name="API呼び出し回数"),
                ),
                (
                    "total_duration",
                    models.IntegerField(default=0, verbose_name="総音声長（秒）"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "使用量ログ",
                "verbose_name_plural": "使用量ログ",
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
