# Generated by Django 5.2 on 2025-06-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="plan_type",
            field=models.CharField(
                choices=[("free", "無料"), ("pro", "有料")],
                default="free",
                max_length=20,
                verbose_name="プラン種別",
            ),
        ),
    ]
