# Generated by Django 5.2 on 2025-06-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_plan_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="api_key",
            field=models.CharField(
                blank=True,
                help_text="外部API連携用のAPIキー",
                max_length=40,
                null=True,
                unique=True,
            ),
        ),
    ]
